{
  "package": "Django",
  "ecosystem": "pypi",
  "total_cves": 255,
  "projects_affected": 4,
  "cves": [
    {
      "cve_id": "GHSA-q95w-c7qg-hrff",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:L/A:N",
      "description": "Django vulnerable to partial directory traversal via archives",
      "published_date": "2025-10-01T21:31:22Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.25'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.13'}\", \"{'introduced': '5.2'}\", \"{'fixed': '5.2.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-hpr9-3m2g-3j9p",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:H/I:L/A:N",
      "description": "Django vulnerable to SQL injection in column aliases",
      "published_date": "2025-10-01T21:31:21Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.25'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.13'}\", \"{'introduced': '5.2'}\", \"{'fixed': '5.2.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6w2r-r2m5-xq5w",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:H/I:L/A:N",
      "description": "Django is subject to SQL injection through its column aliases",
      "published_date": "2025-09-08T18:31:31Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '4.2.24'}\", \"{'introduced': '5.0a1'}\", \"{'fixed': '5.1.12'}\", \"{'introduced': '5.2a1'}\", \"{'fixed': '5.2.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-7xr5-9hcq-chf9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:L/A:N",
      "description": "Django Improper Output Neutralization for Logs vulnerability",
      "published_date": "2025-06-05T03:30:58Z",
      "affected_versions": "[\"{'introduced': '5.2'}\", \"{'fixed': '5.2.2'}\", \"{'introduced': '5.0a1'}\", \"{'fixed': '5.1.10'}\", \"{'introduced': '0'}\", \"{'fixed': '4.2.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2025-47",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.2 before 5.2.2, 5.1 before 5.1.10, and 4.2 before 4.2.22. Internal HTTP response logging does not escape request.path, which allows remote attackers to potentially manipulate log output via crafted URLs. This may lead to log injection or forgery when logs are viewed in terminals or processed by external systems.",
      "published_date": "2025-06-05T03:15:25Z",
      "affected_versions": "[\"{'introduced': '5.2'}\", \"{'fixed': '5.2.2'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.10'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-8j24-cjrq-gr2m",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django has a denial-of-service possibility in strip_tags()",
      "published_date": "2025-05-08T06:30:33Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.21'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.9'}\", \"{'introduced': '5.2'}\", \"{'fixed': '5.2.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2025-37",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 4.2 before 4.2.21, 5.1 before 5.1.9, and 5.2 before 5.2.1. The django.utils.html.strip_tags() function is vulnerable to a potential denial-of-service (slow performance) when processing inputs containing large sequences of incomplete HTML tags. The template filter striptags is also vulnerable, because it is built on top of strip_tags().",
      "published_date": "2025-05-08T04:17:18Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.21'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.9'}\", \"{'introduced': '5.2'}\", \"{'fixed': '5.2.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-wqfg-m96j-85vm",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L",
      "description": "Django Potential Denial of Service (DoS) on Windows ",
      "published_date": "2025-04-02T15:31:37Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.14'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.8'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2025-14",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.1 before 5.1.8 and 5.0 before 5.0.14. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.views.LoginView, django.contrib.auth.views.LogoutView, and django.views.i18n.set_language are subject to a potential denial-of-service attack via certain inputs with a very large number of Unicode characters.",
      "published_date": "2025-04-02T13:15:44Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.8'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.14'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-p3fp-8748-vqfq",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:L",
      "description": "Django vulnerable to Allocation of Resources Without Limits or Throttling",
      "published_date": "2025-03-06T21:31:26Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.20'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.13'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2025-13",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.1 before 5.1.7, 5.0 before 5.0.13, and 4.2 before 4.2.20. The django.utils.text.wrap() method and wordwrap template filter are subject to a potential denial-of-service attack when used with very long strings.",
      "published_date": "2025-03-06T19:15:27Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.7'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.13'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.20'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-qcgg-j2x8-h9g8",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L",
      "description": "Django has a potential denial-of-service vulnerability in IPv6 validation",
      "published_date": "2025-01-14T21:31:47Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.5'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.11'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.18'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.5'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.11'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.18'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2025-1",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and 4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed when performing IPv6 validation could lead to a potential denial-of-service attack. The undocumented and private functions clean_ipv6_address and is_valid_ipv6_address are vulnerable, as is the django.forms.GenericIPAddressField form field. (The django.db.models.GenericIPAddressField model field is not affected.)",
      "published_date": "2025-01-14T19:15:32Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.5'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.11'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.18'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-8498-2h75-472j",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django denial-of-service in django.utils.html.strip_tags()",
      "published_date": "2024-12-06T12:30:47Z",
      "affected_versions": "[\"{'introduced': '5.1.0'}\", \"{'fixed': '5.1.4'}\", \"{'introduced': '4.2.0'}\", \"{'fixed': '4.2.17'}\", \"{'introduced': '5.0.0'}\", \"{'fixed': '5.0.10'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.4'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.10'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.17'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-m9g8-fxxm-xg86",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Django SQL injection in HasKey(lhs, rhs) on Oracle",
      "published_date": "2024-12-06T12:30:47Z",
      "affected_versions": "[\"{'introduced': '5.0.0'}\", \"{'fixed': '5.0.10'}\", \"{'introduced': '5.1.0'}\", \"{'fixed': '5.1.4'}\", \"{'introduced': '4.2.0'}\", \"{'fixed': '4.2.17'}\", \"{'introduced': '5.1'}\", \"{'fixed': '5.1.4'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.10'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.17'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-157",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. Direct usage of the django.db.models.fields.json.HasKey lookup, when an Oracle database is used, is subject to SQL injection if untrusted data is used as an lhs value. (Applications that use the jsonfield.has_key lookup via __ are unaffected.)",
      "published_date": "2024-12-06T12:15:18Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.4'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.10'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.17'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-156",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. The strip_tags() method and striptags template filter are subject to a potential denial-of-service attack via certain inputs containing large sequences of nested incomplete HTML entities.",
      "published_date": "2024-12-06T12:15:17Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.4'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.10'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.17'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-5hgc-2vfp-mqvc",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django vulnerable to denial-of-service attack via the urlize() and urlizetrunc() template filters",
      "published_date": "2024-10-08T18:33:13Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.1'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.9'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.16'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-rrqc-c2jx-6jgv",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "description": "Django allows enumeration of user e-mail addresses",
      "published_date": "2024-10-08T18:33:13Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.1'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.9'}\", \"{'introduced': '0'}\", \"{'fixed': '4.2.16'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-102",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and 4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
      "published_date": "2024-10-08T16:15:00Z",
      "affected_versions": "[\"{'introduced': '5.1'}\", \"{'fixed': '5.1.1'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.9'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.16'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-795c-9xpc-xw6g",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django vulnerable to a denial-of-service attack",
      "published_date": "2024-08-07T15:30:42Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-jh75-99hh-qvx9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django memory consumption vulnerability",
      "published_date": "2024-08-07T15:30:42Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-pv4p-cwwg-4rph",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
      "description": "Django SQL injection vulnerability",
      "published_date": "2024-08-07T15:30:42Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-r836-hh6v-rg5g",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django vulnerable to denial-of-service attack",
      "published_date": "2024-08-07T15:30:42Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-67",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The floatformat template filter is subject to significant memory consumption when given a string representation of a number in scientific notation with a large exponent.",
      "published_date": "2024-08-07T15:15:00Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-68",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
      "published_date": "2024-08-07T15:15:00Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-69",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize and urlizetrunc template filters, and the AdminURLFieldWidget widget, are subject to a potential denial-of-service attack via certain inputs with a very large number of Unicode characters.",
      "published_date": "2024-08-07T15:15:00Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-70",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. QuerySet.values() and values_list() methods on models with a JSONField are subject to SQL injection in column aliases via a crafted JSON object key as a passed *arg.",
      "published_date": "2024-08-07T15:15:00Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.8'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-9jmf-237g-qf46",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Django Path Traversal vulnerability",
      "published_date": "2024-07-10T06:33:52Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-f6f8-9mx6-9mx2",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django vulnerable to Denial of Service",
      "published_date": "2024-07-10T06:33:52Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-qg2p-9jwr-mmqf",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django vulnerable to Denial of Service",
      "published_date": "2024-07-10T06:33:52Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-x7q2-wr7g-xqmf",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "description": "Django vulnerable to user enumeration attack",
      "published_date": "2024-07-10T06:33:52Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-56",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
      "published_date": "2024-07-10T05:15:00Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-57",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password.",
      "published_date": "2024-07-10T05:15:00Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-58",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. Derived classes of the django.core.files.storage.Storage base class, when they override generate_filename() without replicating the file-path validations from the parent class, potentially allow directory traversal via certain inputs during a save() call. (Built-in Storage sub-classes are unaffected.)",
      "published_date": "2024-07-10T05:15:00Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-59",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
      "published_date": "2024-07-10T05:15:00Z",
      "affected_versions": "[\"{'introduced': '5.0'}\", \"{'fixed': '5.0.7'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.14'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-vm8q-m57g-pff3",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "description": "Regular expression denial-of-service in Django",
      "published_date": "2024-03-15T21:30:43Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.25'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.11'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-47",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
      "published_date": "2024-03-15T20:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.25'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.11'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-xxj9-f6rv-m3x4",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django denial-of-service attack in the intcomma template filter",
      "published_date": "2024-02-07T00:30:25Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.24'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.10'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2024-28",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10, and Django 5.0 before 5.0.2. The intcomma template filter was subject to a potential denial-of-service attack when used with very long strings.",
      "published_date": "2024-02-06T22:16:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.24'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.10'}\", \"{'introduced': '5.0'}\", \"{'fixed': '5.0.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-h8gc-pgj2-vjm3",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Denial-of-service in django.utils.text.Truncator",
      "published_date": "2023-11-03T06:36:30Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.22'}\", \"{'introduced': '4.1a1'}\", \"{'fixed': '4.1.12'}\", \"{'introduced': '4.2a1'}\", \"{'fixed': '4.2.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-7h4p-27mh-hmrw",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django Denial of service vulnerability in django.utils.encoding.uri_to_iri",
      "published_date": "2023-11-03T06:36:29Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.21'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.11'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2023-225",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
      "published_date": "2023-11-03T05:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.21'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.11'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2023-226",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 3.2 before 3.2.22, 4.1 before 4.1.12, and 4.2 before 4.2.6, the django.utils.text.Truncator chars() and words() methods (when used with html=True) are subject to a potential DoS (denial of service) attack via certain inputs with very long, potentially malformed HTML text. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which are thus also vulnerable. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232.",
      "published_date": "2023-11-03T05:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.22'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.12'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-qmf9-6jqf-j8fq",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django potential denial of service vulnerability in UsernameField on Windows",
      "published_date": "2023-11-02T06:30:25Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.23'}\", \"{'introduced': '4.1a1'}\", \"{'fixed': '4.1.13'}\", \"{'introduced': '4.2a1'}\", \"{'fixed': '4.2.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2023-222",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
      "published_date": "2023-11-02T06:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.23'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.13'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-jh3w-4vvf-mjgr",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django has regular expression denial of service vulnerability in EmailValidator/URLValidator",
      "published_date": "2023-07-03T15:30:45Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.20'}\", \"{'introduced': '4.0a1'}\", \"{'fixed': '4.1.10'}\", \"{'introduced': '4.2a1'}\", \"{'fixed': '4.2.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2023-100",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, EmailValidator and URLValidator are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs.",
      "published_date": "2023-07-03T13:15:00Z",
      "affected_versions": "[\"{'introduced': '4.2'}\", \"{'fixed': '4.2.3'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.1.10'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.20'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-r3xc-prgr-mg9p",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Django bypasses validation when using one form field to upload multiple files",
      "published_date": "2023-05-07T03:30:17Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.19'}\", \"{'introduced': '4.0a1'}\", \"{'fixed': '4.1.9'}\", \"{'introduced': '4.2a1'}\", \"{'fixed': '4.2.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2023-61",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.",
      "published_date": "2023-05-07T02:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.19'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.1.9'}\", \"{'introduced': '4.2'}\", \"{'fixed': '4.2.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-2hrw-hx67-34x6",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Resource exhaustion in Django",
      "published_date": "2023-02-15T03:30:47Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.18'}\", \"{'introduced': '4.1a1'}\", \"{'fixed': '4.1.7'}\", \"{'introduced': '4.0a1'}\", \"{'fixed': '4.0.10'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2023-13",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in the Multipart Request Parser in Django 3.2 before 3.2.18, 4.0 before 4.0.10, and 4.1 before 4.1.7. Passing certain inputs (e.g., an excessive number of parts) to multipart forms could result in too many open files or memory exhaustion, and provided a potential vector for a denial-of-service attack.",
      "published_date": "2023-02-15T01:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.18'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.10'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-q2jf-h9jm-m7p4",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django contains Uncontrolled Resource Consumption via cached header",
      "published_date": "2023-02-01T21:30:23Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.17'}\", \"{'introduced': '4.0a1'}\", \"{'fixed': '4.0.9'}\", \"{'introduced': '4.1a1'}\", \"{'fixed': '4.1.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2023-12",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 3.2 before 3.2.17, 4.0 before 4.0.9, and 4.1 before 4.1.6, the parsed values of Accept-Language headers are cached in order to avoid repetitive parsing. This leads to a potential denial-of-service vector via excessive memory usage if the raw value of Accept-Language headers is very large.",
      "published_date": "2023-02-01T19:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.17'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.9'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-qrw5-5h28-6cmg",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django denial-of-service vulnerability in internationalized URLs",
      "published_date": "2022-10-16T12:00:23Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.16'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.8'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-304",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression.",
      "published_date": "2022-10-16T06:15:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '5b6b257fa7ec37ff27965358800c67e2dd11c924'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.16'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.8'}\", \"{'introduced': '4.1'}\", \"{'fixed': '4.1.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-8x94-hmjh-97hq",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "description": "Django vulnerable to Reflected File Download attack",
      "published_date": "2022-08-11T14:49:12Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '3.2.15'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-245",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in the HTTP FileResponse class in Django 3.2 before 3.2.15 and 4.0 before 4.0.7. An application is vulnerable to a reflected file download (RFD) attack that sets the Content-Disposition header of a FileResponse when the filename is derived from user-supplied input.",
      "published_date": "2022-08-03T14:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.15'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-p64x-8rxx-wf6q",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Django `Trunc()` and `Extract()` database functions vulnerable to SQL Injection",
      "published_date": "2022-07-05T00:00:53Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.14'}\", \"{'introduced': '4.0a1'}\", \"{'fixed': '4.0.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-213",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 3.2 before 3.2.14 and 4.0 before 4.0.6. The Trunc() and Extract() database functions are subject to SQL injection if untrusted data is used as a kind/lookup_name value. Applications that constrain the lookup name and kind choice to a known safe list are unaffected.",
      "published_date": "2022-07-04T16:15:00Z",
      "affected_versions": "[\"{'introduced': '3.2'}\", \"{'fixed': '3.2.14'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-59w8-4wm2-4xw8",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Image Field Vulnerable to Image Decompression Bombs",
      "published_date": "2022-05-17T05:12:01Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.3.2'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-5h2q-4hrp-v9rr",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django vulnerable to Improper Restriction of Operations within the Bounds of a Memory Buffer",
      "published_date": "2022-05-17T05:12:01Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.3.2'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-78vx-ggch-wghm",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django Allows Redirect via Data URL",
      "published_date": "2022-05-17T05:12:01Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.3.2'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-2655-q453-22f9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Allows Arbitrary URL Generation",
      "published_date": "2022-05-17T05:10:31Z",
      "affected_versions": "[\"{'introduced': '1.3'}\", \"{'fixed': '1.3.4'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-qrh7-x6fp-c2mp",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "XML Entity Expansion (XEE) in Django",
      "published_date": "2022-05-17T05:09:40Z",
      "affected_versions": "[\"{'introduced': '1.3.0'}\", \"{'fixed': '1.3.6'}\", \"{'introduced': '1.4.0'}\", \"{'fixed': '1.4.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-x64m-686f-fmm3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "XML External Entity (XXE) in Django",
      "published_date": "2022-05-17T05:09:39Z",
      "affected_versions": "[\"{'introduced': '1.3.0'}\", \"{'fixed': '1.3.6'}\", \"{'introduced': '1.4.0'}\", \"{'fixed': '1.4.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-vjjp-9r83-22rc",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N",
      "description": "Django Directory Traversal via ssi template tag",
      "published_date": "2022-05-17T04:56:46Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.7'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-4c42-4rxm-x6qf",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Denial of Service Vulnerability in the authentication framework ",
      "published_date": "2022-05-17T04:53:45Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.8'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-46x4-9jmv-jc8p",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:H/A:N",
      "description": "Django Access Restrictions Bypass ",
      "published_date": "2022-05-17T03:43:00Z",
      "affected_versions": "[\"{'introduced': '1.9'}\", \"{'fixed': '1.9.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6565-fg86-6jcx",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django Cross-site Scripting Vulnerability",
      "published_date": "2022-05-17T03:34:12Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.7.6'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8b2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6wgp-fwfm-mxp3",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django allows user sessions hijacking via an empty string in the session key",
      "published_date": "2022-05-17T03:29:56Z",
      "affected_versions": "[\"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6wcr-wcqm-3mfh",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N",
      "description": "Django settings leak in date template filter",
      "published_date": "2022-05-17T03:25:24Z",
      "affected_versions": "[\"{'introduced': '1.7'}\", \"{'fixed': '1.7.11'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.7'}\", \"{'introduced': '1.9a1'}\", \"{'fixed': '1.9rc2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-7qfw-j7hp-v45g",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
      "description": "Django WSGI Header Spoofing Vulnerability",
      "published_date": "2022-05-17T03:20:54Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.18'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6g95-x6cj-mg4v",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django database denial-of-service with ModelMultipleChoiceField",
      "published_date": "2022-05-17T03:20:50Z",
      "affected_versions": "[\"{'introduced': '1.6'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-jhjg-w2cp-5j44",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django DoS in django.views.static.serve",
      "published_date": "2022-05-17T03:20:50Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.18'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-gv98-g628-m9x5",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django Cross-site Scripting Vulnerability",
      "published_date": "2022-05-17T03:20:49Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.18'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-x38m-486c-2wr9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Denial-of-service possibility in logout() view by filling session store",
      "published_date": "2022-05-17T03:16:12Z",
      "affected_versions": "[\"{'introduced': '1.7'}\", \"{'fixed': '1.7.10'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-89hj-xfx5-7q66",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Django Reuses Cached CSRF Token",
      "published_date": "2022-05-17T03:07:04Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.11'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.6'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-rvq6-mrpv-m6rm",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Code Injection in Django",
      "published_date": "2022-05-17T03:07:04Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.11'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.6'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-wqjj-hx84-v449",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Django Vulnerable to MySQL Injection",
      "published_date": "2022-05-17T03:07:04Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.11'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.6'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-q7q2-qf2q-rw3w",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
      "description": "Django Vulnerable to Cache Poisoning",
      "published_date": "2022-05-17T03:07:00Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.13'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.8'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.5'}\", \"{'introduced': '1.7a1'}\", \"{'fixed': '1.7b4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-4894-5vqc-6r2r",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django cross-site scripting (XSS) vulnerability in the AdminURLFieldWidget widget",
      "published_date": "2022-05-17T01:33:07Z",
      "affected_versions": "[\"{'introduced': '1.5'}\", \"{'fixed': '1.5.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-fp6p-5xvw-m74f",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N",
      "description": "Django User Enumeration Vulnerability",
      "published_date": "2022-05-17T01:09:58Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.8.10'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-pw27-w7w4-9qc7",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:H/A:N",
      "description": "Django XSS Vulnerability",
      "published_date": "2022-05-17T01:09:58Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.8.10'}\", \"{'introduced': '1.9a1'}\", \"{'fixed': '1.9.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-cqf7-ff9h-7967",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django ReDoS in validators.URLValidator",
      "published_date": "2022-05-17T00:48:30Z",
      "affected_versions": "[\"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-q5qw-4364-5hhm",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Vulnerable to HTTP Response Splitting Attack",
      "published_date": "2022-05-17T00:48:30Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.21'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.7.9'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-pgxh-wfw4-jx2v",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django denial of service via empty session record creation",
      "published_date": "2022-05-17T00:36:02Z",
      "affected_versions": "[\"{'introduced': '1.8'}\", \"{'fixed': '1.8.4'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.10'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-3f2c-jm6v-cr35",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Django DNS Rebinding Vulnerability",
      "published_date": "2022-05-17T00:27:18Z",
      "affected_versions": "[\"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.16'}\", \"{'introduced': '1.9a1'}\", \"{'fixed': '1.9.11'}\", \"{'introduced': '1.10a1'}\", \"{'fixed': '1.10.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-mv8g-fhh6-6267",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Django user with hardcoded password created when running tests on Oracle",
      "published_date": "2022-05-17T00:27:18Z",
      "affected_versions": "[\"{'introduced': '1.10a1'}\", \"{'fixed': '1.10.3'}\", \"{'introduced': '1.9a1'}\", \"{'fixed': '1.9.11'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.16'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-9cwg-mhxf-hh59",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django cross-site scripting (XSS) vulnerability via is_safe_url function ",
      "published_date": "2022-05-17T00:23:23Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.6'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-crhm-qpjc-cm64",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django CSRF Protection Bypass",
      "published_date": "2022-05-14T03:55:50Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.8.15'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.10'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-rm2j-x595-q9cj",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Vulnerable to Cache Poisoning",
      "published_date": "2022-05-14T03:49:36Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-wxg3-mfph-qg9w",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Might Allow CSRF Requests via URL Verification",
      "published_date": "2022-05-14T03:49:36Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-c8c8-9472-w52h",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django Cross-site scripting Vulnerability",
      "published_date": "2022-05-14T02:46:13Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.8.14'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.8'}\", \"{'introduced': '1.10a1'}\", \"{'fixed': '1.10rc1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-vq3h-3q7v-9prw",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Allows Open Redirects",
      "published_date": "2022-05-14T02:09:43Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.13'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.8'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.5'}\", \"{'introduced': '1.7a1'}\", \"{'fixed': '1.7b4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-625g-gx8c-xcmg",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Middleware Enables Session Hijacking",
      "published_date": "2022-05-14T02:09:22Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\", \"{'introduced': '1.7a1'}\", \"{'fixed': '1.7c3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-f7cm-ccfp-3q4r",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Incorrectly Validates URLs",
      "published_date": "2022-05-14T02:09:22Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-rw75-m7gp-92m3",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "description": "Django data leakage via querystring manipulation in admin",
      "published_date": "2022-05-14T02:09:22Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\", \"{'introduced': '1.7a1'}\", \"{'fixed': '1.7c3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-j3j3-jrfh-cm2w",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Denial-of-service possibility with strip_tags",
      "published_date": "2022-05-14T02:06:52Z",
      "affected_versions": "[\"{'introduced': '1.6'}\", \"{'fixed': '1.6.11'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.7'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8c1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-7fq8-4pv5-5w5c",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django cross-site scripting (XSS) attack via user-supplied redirect URLs",
      "published_date": "2022-05-14T02:06:51Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.20'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.6.11'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.7'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8c1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-296w-6qhq-gf92",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django denial of service via file upload naming",
      "published_date": "2022-05-14T02:05:08Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-r7w6-p47g-vj53",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
      "description": "Django Data leakage via admin history log",
      "published_date": "2022-05-05T02:48:46Z",
      "affected_versions": "[\"{'introduced': '1.3'}\", \"{'fixed': '1.3.6'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-g8xg-jgj6-49r3",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django is vulnerable to Denial of Service attack in formset ",
      "published_date": "2022-05-05T02:48:45Z",
      "affected_versions": "[\"{'introduced': '1.3'}\", \"{'fixed': '1.3.6'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-p6m5-h7pp-v2x5",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Regex Algorithmic Complexity Causes Denial of Service",
      "published_date": "2022-05-02T03:47:43Z",
      "affected_versions": "[\"{'introduced': '1.0'}\", \"{'fixed': '1.0.4'}\", \"{'introduced': '1.1'}\", \"{'fixed': '1.1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-9xg7-gg9m-rmq9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Django Admin Media Handler Vulnerable to Directory Traversal",
      "published_date": "2022-05-02T03:37:17Z",
      "affected_versions": "[\"{'introduced': '0.96.0'}\", \"{'fixed': '0.96.4'}\", \"{'introduced': '1.0'}\", \"{'fixed': '1.0.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-r5cj-wv24-92p5",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django cross-site request forgery (CSRF) vulnerability",
      "published_date": "2022-05-02T00:05:00Z",
      "affected_versions": "[\"{'introduced': '0.91.0'}\", \"{'fixed': '0.91.3'}\", \"{'introduced': '0.95.0'}\", \"{'fixed': '0.95.4'}\", \"{'introduced': '0.96.0'}\", \"{'fixed': '0.96.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-54qj-48vx-cr9f",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django Cross-site scripting (XSS) vulnerability",
      "published_date": "2022-05-01T23:48:43Z",
      "affected_versions": "[\"{'introduced': '0.91'}\", \"{'fixed': '0.91.2'}\", \"{'introduced': '0.95'}\", \"{'fixed': '0.95.3'}\", \"{'introduced': '0.96'}\", \"{'fixed': '0.96.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-9v8h-57gv-qch6",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django vulnerable to Denial of Service via i18n middleware component",
      "published_date": "2022-05-01T18:36:08Z",
      "affected_versions": "[\"{'introduced': '0.96.0'}\", \"{'fixed': '0.96.1'}\", \"{'introduced': '0.95'}\", \"{'fixed': '0.95.2'}\", \"{'introduced': '0.91.0'}\", \"{'fixed': '0.91.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-mwv2-398h-v489",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django Improper Access Control",
      "published_date": "2022-05-01T17:44:04Z",
      "affected_versions": "[\"{'introduced': '0.95'}\", \"{'fixed': '1.0'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-qc99-g3wm-hgxr",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django Arbitrary Code Execution",
      "published_date": "2022-05-01T17:44:04Z",
      "affected_versions": "[\"{'introduced': '0.95'}\", \"{'fixed': '1.0'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-2gwj-7jmv-h26r",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "SQL Injection in Django",
      "published_date": "2022-04-13T00:00:33Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.28'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.13'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-w24h-v9qh-8gxj",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "SQL Injection in Django",
      "published_date": "2022-04-13T00:00:33Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.28'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.13'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-190",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. QuerySet.annotate(), aggregate(), and extra() methods are subject to SQL injection in column aliases via a crafted dictionary (with dictionary expansion) as the passed **kwargs.",
      "published_date": "2022-04-12T05:15:00Z",
      "affected_versions": "[\"{'introduced': '4.0'}\", \"{'fixed': '4.0.4'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.13'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.28'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-191",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "A SQL injection issue was discovered in QuerySet.explain() in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. This occurs by passing a crafted dictionary (with dictionary expansion) as the **options argument, and placing the injection payload in an option name.",
      "published_date": "2022-04-12T05:15:00Z",
      "affected_versions": "[\"{'introduced': '4.0'}\", \"{'fixed': '4.0.4'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.13'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.28'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-95rw-fx8r-36v6",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Cross-site Scripting in Django",
      "published_date": "2022-02-04T00:00:33Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.27'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.12'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6cw3-g6wv-c2xv",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Infinite Loop in Django",
      "published_date": "2022-02-04T00:00:26Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.27'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.12'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-19",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The {% debug %} template tag in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2 does not properly encode the current context. This may lead to XSS.",
      "published_date": "2022-02-03T02:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.27'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.12'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-20",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in MultiPartParser in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2. Passing certain inputs to multipart forms could result in an infinite loop when parsing files.",
      "published_date": "2022-02-03T02:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.27'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.12'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-8c5j-9r9f-c6w8",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Information disclosure in Django",
      "published_date": "2022-01-12T19:21:10Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.26'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.11'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-jrh2-hc4r-7jwx",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "description": "Directory-traversal in Django",
      "published_date": "2022-01-12T19:21:04Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.26'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.11'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-53qw-q765-4fww",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Denial-of-service in Django",
      "published_date": "2022-01-12T19:20:53Z",
      "affected_versions": "[\"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.26'}\", \"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.11'}\", \"{'introduced': '4.0a1'}\", \"{'fixed': '4.0.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-1",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.",
      "published_date": "2022-01-05T00:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.26'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.11'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-2",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution logic, the dictsort template filter was potentially vulnerable to information disclosure, or an unintended method call, if passed a suitably crafted key.",
      "published_date": "2022-01-05T00:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.26'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.11'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2022-3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.",
      "published_date": "2022-01-05T00:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.26'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.11'}\", \"{'introduced': '4.0'}\", \"{'fixed': '4.0.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-v6rh-hp5x-86rv",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
      "description": "Potential bypass of an upstream access control based on URL paths in Django",
      "published_date": "2021-12-09T19:09:37Z",
      "affected_versions": "[\"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.25'}\", \"{'introduced': '3.0a1'}\", \"{'fixed': '3.1.14'}\", \"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.10'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-439",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths.",
      "published_date": "2021-12-08T00:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.25'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.14'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.10'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-xpfp-f569-q3p2",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "SQL Injection in Django",
      "published_date": "2021-09-22T17:34:49Z",
      "affected_versions": "[\"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.5'}\", \"{'introduced': '3.0a1'}\", \"{'fixed': '3.1.13'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-109",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.order_by SQL injection if order_by is untrusted input from a client of a web application.",
      "published_date": "2021-07-02T10:15:00Z",
      "affected_versions": "[\"{'introduced': '3.1'}\", \"{'fixed': '3.1.13'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-p99v-5w3c-jqq9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Access Control Bypass possibly leading to SSRF, RFI, and LFI attacks ",
      "published_date": "2021-06-10T17:21:12Z",
      "affected_versions": "[\"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.24'}\", \"{'introduced': '3.0a1'}\", \"{'fixed': '3.1.12'}\", \"{'introduced': '3.2a1'}\", \"{'fixed': '3.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-68w8-qjq3-2gfm",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
      "description": "Path Traversal in Django",
      "published_date": "2021-06-10T17:21:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '2.2.24'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.1.12'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-qm57-vhq3-3fwf",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Header injection possible in Django",
      "published_date": "2021-06-09T17:14:51Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.22'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.10'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-98",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django before 2.2.24, 3.x before 3.1.12, and 3.2.x before 3.2.4 has a potential directory traversal via django.contrib.admindocs. Staff members could use the TemplateDetailView view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by application developers to also show file contents, then not only the existence but also the file contents would have been exposed. In other words, there is directory traversal outside of the template root directories.",
      "published_date": "2021-06-08T18:15:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '2.2.24'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.1.12'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-99",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 2.2 before 2.2.24, 3.x before 3.1.12, and 3.2 before 3.2.4, URLValidator, validate_ipv4_address, and validate_ipv46_address do not prohibit leading zero characters in octal literals. This may allow a bypass of access control that is based on IP addresses. (validate_ipv4_address and validate_ipv46_address are unaffected with Python 3.9.5+..) .",
      "published_date": "2021-06-08T18:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.24'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.1.12'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-rxjp-mfm9-w4wr",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Path Traversal in Django",
      "published_date": "2021-06-04T21:15:56Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.21'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.1.9'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-8",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.",
      "published_date": "2021-05-06T16:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.22'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.10'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-7",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names.",
      "published_date": "2021-05-05T15:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.21'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.9'}\", \"{'introduced': '3.2'}\", \"{'fixed': '3.2.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-xgxc-v2qg-chmh",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "description": "Directory Traversal in Django",
      "published_date": "2021-04-08T18:11:48Z",
      "affected_versions": "[\"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.20'}\", \"{'introduced': '3.0a1'}\", \"{'fixed': '3.0.14'}\", \"{'introduced': '3.1a1'}\", \"{'fixed': '3.1.8'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-6",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 2.2 before 2.2.20, 3.0 before 3.0.14, and 3.1 before 3.1.8, MultiPartParser allowed directory traversal via uploaded files with suitably crafted file names. Built-in upload handlers were not affected by this vulnerability.",
      "published_date": "2021-04-06T15:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.20'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.14'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.8'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-m6gj-h9gm-gw44",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Django Incorrect Default Permissions",
      "published_date": "2021-03-18T20:30:13Z",
      "affected_versions": "[\"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.16'}\", \"{'introduced': '3.0a1'}\", \"{'fixed': '3.0.10'}\", \"{'introduced': '3.1a1'}\", \"{'fixed': '3.1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-fr28-569j-53c4",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Django Incorrect Default Permissions",
      "published_date": "2021-03-18T20:30:01Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.16'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.10'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-fvgf-6h6h-3322",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
      "description": "Django Directory Traversal via archive.extract",
      "published_date": "2021-03-18T20:29:49Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.18'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.6'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.12'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2021-9",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 2.2 before 2.2.18, 3.0 before 3.0.12, and 3.1 before 3.1.6, the django.utils.archive.extract method (used by \"startapp --template\" and \"startproject --template\") allows directory traversal via an archive with absolute paths or relative paths with dot segments.",
      "published_date": "2021-02-02T07:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.18'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.12'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2020-33",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.",
      "published_date": "2020-09-01T13:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.16'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.10'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2020-34",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077.",
      "published_date": "2020-09-01T13:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.16'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.10'}\", \"{'introduced': '3.1'}\", \"{'fixed': '3.1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-2m34-jcjv-45xf",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "XSS in Django",
      "published_date": "2020-06-05T16:24:28Z",
      "affected_versions": "[\"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.13'}\", \"{'introduced': '3.0a1'}\", \"{'fixed': '3.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-wpjr-j57x-wxfw",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Data leakage via cache key collision in Django",
      "published_date": "2020-06-05T16:20:44Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.13'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-3gh2-xw74-jmcw",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
      "description": "SQL injection in Django",
      "published_date": "2020-06-05T14:52:07Z",
      "affected_versions": "[\"{'introduced': '1.11'}\", \"{'fixed': '1.11.29'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.11'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2020-31",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.",
      "published_date": "2020-06-03T14:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.13'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2020-32",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.",
      "published_date": "2020-06-03T14:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.13'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2020-36",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.11 before 1.11.29, 2.2 before 2.2.11, and 3.0 before 3.0.4 allows SQL Injection if untrusted data is used as a tolerance parameter in GIS functions and aggregates on Oracle. By passing a suitably crafted tolerance to GIS functions and aggregates on Oracle, it was possible to break escaping and inject malicious SQL.",
      "published_date": "2020-03-05T15:15:00Z",
      "affected_versions": "[\"{'introduced': '1.11'}\", \"{'fixed': '1.11.29'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.11'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-hmr4-m2h5-33qx",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "SQL injection in Django",
      "published_date": "2020-02-11T21:03:20Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.11.28'}\", \"{'introduced': '2.0'}\", \"{'fixed': '2.2.10'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2020-35",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.",
      "published_date": "2020-02-03T12:15:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': 'eb31d845323618d688ad429479c6dda973056136'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.28'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.10'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-vfq6-hq5r-27r6",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "Django Potential account hijack via password reset form",
      "published_date": "2020-01-16T22:35:12Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.11.27'}\", \"{'introduced': '2.0'}\", \"{'fixed': '2.2.9'}\", \"{'introduced': '3.0'}\", \"{'fixed': '3.0.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-16",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)",
      "published_date": "2019-12-18T19:15:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.11.27'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.9'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-hvmf-r92r-27hr",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django allows unintended model editing",
      "published_date": "2019-12-04T21:26:28Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.15'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.8'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-15",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 2.1 before 2.1.15 and 2.2 before 2.2.8 allows unintended model editing. A Django model admin displaying inline related models, where the user has view-only permissions to a parent model but edit permissions to the inline model, would be presented with an editing UI, allowing POST requests, for updating the inline model. Directly editing the view-only parent model was not possible, but the parent model's save() method was called, triggering potential side effects, and causing pre and post-save signal handlers to be invoked. (To resolve this, the Django admin is adjusted to require edit permissions on the parent model in order for inline models to be editable.)",
      "published_date": "2019-12-02T14:15:00Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.15'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.8'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6r97-cj55-9hrq",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "description": "SQL Injection in Django",
      "published_date": "2019-08-16T14:00:34Z",
      "affected_versions": "[\"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.23'}\", \"{'introduced': '2.1a1'}\", \"{'fixed': '2.1.11'}\", \"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-13",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.",
      "published_date": "2019-08-09T13:15:00Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.11'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.23'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-h5jv-4p7w-64jg",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Denial-of-service in strip_tags()",
      "published_date": "2019-08-06T01:43:33Z",
      "affected_versions": "[\"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.23'}\", \"{'introduced': '2.1a1'}\", \"{'fixed': '2.1.11'}\", \"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-v9qg-3j8p-r63v",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Uncontrolled Recursion in Django",
      "published_date": "2019-08-06T01:43:31Z",
      "affected_versions": "[\"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.23'}\", \"{'introduced': '2.1a1'}\", \"{'fixed': '2.1.11'}\", \"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-c4qh-4vgv-qc6g",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Denial-of-service in django.utils.text.Truncator",
      "published_date": "2019-08-06T01:43:29Z",
      "affected_versions": "[\"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.23'}\", \"{'introduced': '2.1a1'}\", \"{'fixed': '2.1.11'}\", \"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-11",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If django.utils.text.Truncator's chars() and words() methods were passed the html=True argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which were thus vulnerable.",
      "published_date": "2019-08-02T15:15:00Z",
      "affected_versions": "[\"{'introduced': '1.11'}\", \"{'fixed': '1.11.23'}\", \"{'introduced': '2.1'}\", \"{'fixed': '2.1.11'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-12",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.",
      "published_date": "2019-08-02T15:15:00Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.11'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.4'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.23'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-14",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.",
      "published_date": "2019-08-02T15:15:00Z",
      "affected_versions": "[\"{'introduced': '2.2'}\", \"{'fixed': '2.2.4'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.23'}\", \"{'introduced': '2.1'}\", \"{'fixed': '2.1.11'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-h582-2pch-3xv3",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Django Denial-of-service by filling session store",
      "published_date": "2019-07-05T21:10:39Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.21'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.7.9'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6c7v-2f49-8h26",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "description": "Django Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
      "published_date": "2019-07-03T20:37:25Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.10'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.3'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-10",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.",
      "published_date": "2019-07-01T14:15:00Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.10'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.3'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-7rp2-fm2h-wchj",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django Cross-site Scripting in AdminURLFieldWidget",
      "published_date": "2019-06-10T18:43:25Z",
      "affected_versions": "[\"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.21'}\", \"{'introduced': '2.1a1'}\", \"{'fixed': '2.1.9'}\", \"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-79",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 1.11 before 1.11.21, 2.1 before 2.1.9, and 2.2 before 2.2.2. The clickable Current URL value displayed by the AdminURLFieldWidget displays the provided value without validating it as a safe URL. Thus, an unvalidated value stored in the database, or a value provided as a URL query parameter payload, could result in an clickable JavaScript link.",
      "published_date": "2019-06-03T17:29:00Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.9'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.21'}\", \"{'introduced': '2.2'}\", \"{'fixed': '2.2.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6c3j-c64m-qhgq",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "XSS in jQuery as used in Drupal, Backdrop CMS, and other products",
      "published_date": "2019-04-26T16:29:11Z",
      "affected_versions": "[\"{'introduced': '1.1.4'}\", \"{'fixed': '3.4.0'}\", \"{'introduced': '0'}\", \"{'fixed': '4.3.4'}\", \"{'introduced': '1.1.4'}\", \"{'fixed': '3.4.0'}\", \"{'introduced': '2.0a1'}\", \"{'fixed': '2.1.9'}\", \"{'introduced': '2.2a1'}\", \"{'fixed': '2.2.2'}\", \"{'introduced': '1.1.4'}\", \"{'fixed': '3.4.0'}\", \"{'introduced': '0'}\", \"{'fixed': '1.19.0'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-wh4h-v3f2-r2pp",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Uncontrolled Memory Consumption in Django",
      "published_date": "2019-02-12T15:36:37Z",
      "affected_versions": "[\"{'introduced': '1.11'}\", \"{'fixed': '1.11.19'}\", \"{'introduced': '2.0'}\", \"{'fixed': '2.0.11'}\", \"{'introduced': '2.1'}\", \"{'fixed': '2.1.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-18",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function.",
      "published_date": "2019-02-11T13:29:00Z",
      "affected_versions": "[\"{'introduced': '1.11'}\", \"{'fixed': '1.11.19'}\", \"{'introduced': '2.0'}\", \"{'fixed': '2.0.12'}\", \"{'introduced': '2.1'}\", \"{'fixed': '2.1.7'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-337x-4q8g-prc5",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
      "description": "Improper Input Validation in Django",
      "published_date": "2019-01-14T16:20:05Z",
      "affected_versions": "[\"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.18'}\", \"{'introduced': '2.0a1'}\", \"{'fixed': '2.0.10'}\", \"{'introduced': '2.1a1'}\", \"{'fixed': '2.1.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2019-17",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.",
      "published_date": "2019-01-09T23:29:00Z",
      "affected_versions": "[\"{'introduced': '1.11'}\", \"{'fixed': '1.11.18'}\", \"{'introduced': '2.0'}\", \"{'fixed': '2.0.10'}\", \"{'introduced': '2.1'}\", \"{'fixed': '2.1.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-9r8w-6x8c-6jr9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django vulnerable to XSS on 500 pages",
      "published_date": "2019-01-04T17:50:34Z",
      "affected_versions": "[\"{'introduced': '1.10a1'}\", \"{'fixed': '1.10.8'}\", \"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-37hp-765x-j95x",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django open redirect and possible XSS attack via user-supplied numeric redirect URLs",
      "published_date": "2019-01-04T17:50:26Z",
      "affected_versions": "[\"{'introduced': '1.10a1'}\", \"{'fixed': '1.10.7'}\", \"{'introduced': '1.9a1'}\", \"{'fixed': '1.9.13'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.18'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-h4hv-m4h4-mhwg",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django open redirect",
      "published_date": "2019-01-04T17:50:17Z",
      "affected_versions": "[\"{'introduced': '1.10'}\", \"{'fixed': '1.10.7'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.13'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.18'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-r28v-mw67-m5p9",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django denial-of-service possibility in urlize and urlizetrunc template filters",
      "published_date": "2019-01-04T17:50:07Z",
      "affected_versions": "[\"{'introduced': '2.0a1'}\", \"{'fixed': '2.0.3'}\", \"{'introduced': '1.11a1'}\", \"{'fixed': '1.11.11'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8.19'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-2f9x-5v75-3qv4",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "description": "Django Denial-of-service possibility in truncatechars_html and truncatewords_html template filters",
      "published_date": "2019-01-04T17:50:00Z",
      "affected_versions": "[\"{'introduced': '2.0'}\", \"{'fixed': '2.0.3'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.11'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.19'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-5hg3-6c2f-f3wr",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Django open redirect",
      "published_date": "2018-10-04T21:58:46Z",
      "affected_versions": "[\"{'introduced': '2.0'}\", \"{'fixed': '2.0.8'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-rf4j-j272-fj86",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "description": "Django vulnerable to information leakage in AuthenticationForm",
      "published_date": "2018-10-03T21:13:54Z",
      "affected_versions": "[\"{'introduced': '2.0a1'}\", \"{'fixed': '2.0.2'}\", \"{'introduced': '1.11.8'}\", \"{'fixed': '1.11.10'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-6mx3-3vqg-hpp2",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
      "description": "Django allows unprivileged users to read the password hashes of arbitrary accounts",
      "published_date": "2018-10-03T20:07:39Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2018-3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.1 before 2.1.2, in which unprivileged users can read the password hashes of arbitrary accounts. The read-only password widget used by the Django Admin to display an obfuscated password hash was bypassed if a user has only the \"view\" permission (new in Django 2.1), resulting in display of the entire password hash to those users. This may result in a vulnerability for sites with legacy user accounts using insecure hashes.",
      "published_date": "2018-10-02T18:29:00Z",
      "affected_versions": "[\"{'introduced': '2.1'}\", \"{'fixed': '2.1.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2018-2",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "django.middleware.common.CommonMiddleware in Django 1.11.x before 1.11.15 and 2.0.x before 2.0.8 has an Open Redirect.",
      "published_date": "2018-08-03T17:29:00Z",
      "affected_versions": "[\"{'introduced': '2.0'}\", \"{'fixed': '2.0.8'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.15'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-8m3r-rv5g-fcpq",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Cross-site scripting in django",
      "published_date": "2018-07-23T21:01:00Z",
      "affected_versions": "[\"{'introduced': '1.1'}\", \"{'fixed': '1.1.4'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-fxpg-gg9g-76gj",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "description": "Cross-site scripting in django",
      "published_date": "2018-07-23T19:52:42Z",
      "affected_versions": "[\"{'introduced': '1.2'}\", \"{'fixed': '1.2.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-x88j-93vc-wpmp",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
      "description": "Session manipulation in Django",
      "published_date": "2018-07-23T19:52:39Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-7g9h-c88w-r7h2",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
      "description": "Directory traversal in Django",
      "published_date": "2018-07-23T19:52:31Z",
      "affected_versions": "[\"{'introduced': '1.1'}\", \"{'fixed': '1.1.4'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-7wph-fc4w-wqp2",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Improper date handling in Django",
      "published_date": "2018-07-23T19:51:59Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1.3'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-fwr5-q9rx-294f",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
      "description": "Improper query string handling in Django",
      "published_date": "2018-07-23T19:51:40Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1.3'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-3jqw-crqj-w8qw",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "description": "Denial of service in django",
      "published_date": "2018-07-23T19:51:35Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-h95j-h2rv-qrg4",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Django Cross-Site Request Forgery vulnerability",
      "published_date": "2018-07-23T19:51:19Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'introduced': '1.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "GHSA-5j2h-h5hg-3wf8",
      "severity": "CVSS_V3",
      "cvss_score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "description": "Cross-site request forgery in Django",
      "published_date": "2018-07-23T19:51:10Z",
      "affected_versions": "[\"{'introduced': '1.1'}\", \"{'fixed': '1.1.4'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2018-5",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.0 before 2.0.3, 1.11 before 1.11.11, and 1.8 before 1.8.19. The django.utils.html.urlize() function was extremely slow to evaluate certain inputs due to catastrophic backtracking vulnerabilities in two regular expressions (only one regular expression for Django 1.8.x). The urlize() function is used to implement the urlize and urlizetrunc template filters, which were thus vulnerable.",
      "published_date": "2018-03-09T20:29:00Z",
      "affected_versions": "[\"{'introduced': '1.8'}\", \"{'fixed': '1.8.19'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.11'}\", \"{'introduced': '2.0'}\", \"{'fixed': '2.0.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2018-6",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "An issue was discovered in Django 2.0 before 2.0.3, 1.11 before 1.11.11, and 1.8 before 1.8.19. If django.utils.text.Truncator's chars() and words() methods were passed the html=True argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which were thus vulnerable.",
      "published_date": "2018-03-09T20:29:00Z",
      "affected_versions": "[\"{'introduced': '1.8'}\", \"{'fixed': '1.8.19'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.11'}\", \"{'introduced': '2.0'}\", \"{'fixed': '2.0.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2018-4",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "django.contrib.auth.forms.AuthenticationForm in Django 2.0 before 2.0.2, and 1.11.8 and 1.11.9, allows remote attackers to obtain potentially sensitive information by leveraging data exposure from the confirm_login_allowed() method, as demonstrated by discovering whether a user account is inactive.",
      "published_date": "2018-02-05T03:29:00Z",
      "affected_versions": "[\"{'introduced': '2.0'}\", \"{'fixed': '2.0.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2017-44",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "In Django 1.10.x before 1.10.8 and 1.11.x before 1.11.5, HTML autoescaping was disabled in a portion of the template for the technical 500 debug page. Given the right circumstances, this allowed a cross-site scripting attack. This vulnerability shouldn't affect most production sites since you shouldn't run with \"DEBUG = True\" (which makes this page accessible) in your production settings.",
      "published_date": "2017-09-07T13:29:00Z",
      "affected_versions": "[\"{'introduced': '1.10'}\", \"{'fixed': '1.10.8'}\", \"{'introduced': '1.11'}\", \"{'fixed': '1.11.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2017-10",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "A maliciously crafted URL to a Django (1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18) site using the ``django.views.static.serve()`` view could redirect to any other domain, aka an open redirect vulnerability.",
      "published_date": "2017-04-04T17:59:00Z",
      "affected_versions": "[\"{'introduced': '1.10'}\", \"{'fixed': '1.10.7'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.13'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.18'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2017-9",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely ``django.utils.http.is_safe_url()``) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on ``is_safe_url()`` to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.",
      "published_date": "2017-04-04T17:59:00Z",
      "affected_versions": "[\"{'introduced': '1.10'}\", \"{'fixed': '1.10.7'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.13'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.18'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2016-17",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3 use a hardcoded password for a temporary database user created when running tests with an Oracle database, which makes it easier for remote attackers to obtain access to the database server by leveraging failure to manually specify a password in the database settings TEST dictionary.",
      "published_date": "2016-12-09T20:59:00Z",
      "affected_versions": "[\"{'introduced': '1.8'}\", \"{'fixed': '1.8.16'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.11'}\", \"{'introduced': '1.10'}\", \"{'fixed': '1.10.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2016-18",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.",
      "published_date": "2016-12-09T20:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.8.16'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.11'}\", \"{'introduced': '1.10'}\", \"{'fixed': '1.10.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2016-3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The cookie parsing code in Django before 1.8.15 and 1.9.x before 1.9.10, when used on a site with Google Analytics, allows remote attackers to bypass an intended CSRF protection mechanism by setting arbitrary cookies.",
      "published_date": "2016-10-03T18:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.8.15'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.10'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2016-2",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Cross-site scripting (XSS) vulnerability in the dismissChangeRelatedObjectPopup function in contrib/admin/static/admin/js/admin/RelatedObjectLookups.js in Django before 1.8.14, 1.9.x before 1.9.8, and 1.10.x before 1.10rc1 allows remote attackers to inject arbitrary web script or HTML via vectors involving unsafe usage of Element.innerHTML.",
      "published_date": "2016-08-05T15:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': 'd03bf6fe4e9bf5b07de62c1a271c4b41a7d3d158'}\", \"{'fixed': 'f68e5a99164867ab0e071a936470958ed867479d'}\", \"{'introduced': '0'}\", \"{'fixed': '1.8.14'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.8'}\", \"{'introduced': '1.10a0'}\", \"{'fixed': '1.10rc1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2016-15",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
      "published_date": "2016-04-08T15:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': 'c5544d289233f501917e25970c03ed444abbd4f0'}\", \"{'introduced': '0'}\", \"{'fixed': '1.8.10'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2016-16",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The password hasher in contrib/auth/hashers.py in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to enumerate users via a timing attack involving login requests.",
      "published_date": "2016-04-08T15:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '67b46ba7016da2d259c1ecc7d666d11f5e1cfaab'}\", \"{'introduced': '0'}\", \"{'fixed': '1.8.10'}\", \"{'introduced': '1.9'}\", \"{'fixed': '1.9.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2016-14",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.9.x before 1.9.2, when ModelAdmin.save_as is set to True, allows remote authenticated users to bypass intended access restrictions and create ModelAdmin objects via the \"Save as New\" option when editing objects and leveraging the \"change\" permission.",
      "published_date": "2016-02-08T19:59:00Z",
      "affected_versions": "[\"{'introduced': '1.9'}\", \"{'fixed': '1.9.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-11",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The get_format function in utils/formats.py in Django before 1.7.x before 1.7.11, 1.8.x before 1.8.7, and 1.9.x before 1.9rc2 might allow remote attackers to obtain sensitive application secrets via a settings key in place of a date/time format setting, as demonstrated by SECRET_KEY.",
      "published_date": "2015-12-07T20:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '316bc3fc9437c5960c24baceb93c73f1939711e4'}\", \"{'introduced': '0'}\", \"{'fixed': '1.7.11'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.7'}\", \"{'introduced': '1.9a0'}\", \"{'fixed': '1.9rc2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-22",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "contrib.sessions.middleware.SessionMiddleware in Django 1.8.x before 1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows remote attackers to cause a denial of service (session store consumption or session record removal) via a large number of requests to contrib.auth.views.logout, which triggers the creation of an empty session record.",
      "published_date": "2015-08-24T14:59:00Z",
      "affected_versions": "[\"{'introduced': '1.8'}\", \"{'fixed': '1.8.4'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.10'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-23",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The (1) contrib.sessions.backends.base.SessionBase.flush and (2) cache_db.SessionStore.flush functions in Django 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions create empty sessions in certain circumstances, which allows remote attackers to cause a denial of service (session store consumption) via unspecified vectors.",
      "published_date": "2015-08-24T14:59:00Z",
      "affected_versions": "[\"{'introduced': '1.7'}\", \"{'fixed': '1.7.10'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.22'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-10",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers to inject arbitrary headers and conduct HTTP response splitting attacks via a newline character in an (1) email message to the EmailValidator, a (2) URL to the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4) validate_slug validator.",
      "published_date": "2015-07-14T17:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.21'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.7.9'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-20",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The session backends in Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (session store consumption) via multiple requests with unique session keys.",
      "published_date": "2015-07-14T17:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.21'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.7.9'}\", \"{'introduced': '1.8'}\", \"{'fixed': '1.8.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-21",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
      "published_date": "2015-07-14T17:59:00Z",
      "affected_versions": "[\"{'introduced': '1.8'}\", \"{'fixed': '1.8.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-19",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The session.flush function in the cached_db backend in Django 1.8.x before 1.8.2 does not properly flush the session, which allows remote attackers to hijack user sessions via an empty string in the session key.",
      "published_date": "2015-06-02T14:59:00Z",
      "affected_versions": "[\"{'introduced': '1.8'}\", \"{'fixed': '1.8.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-18",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The utils.html.strip_tags function in Django 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1, when using certain versions of Python, allows remote attackers to cause a denial of service (infinite loop) by increasing the length of the input string.",
      "published_date": "2015-03-25T14:59:00Z",
      "affected_versions": "[\"{'introduced': '1.6'}\", \"{'fixed': '1.6.11'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.7'}\", \"{'introduced': '1.8a0'}\", \"{'fixed': '1.8c1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-9",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The utils.http.is_safe_url function in Django before 1.4.20, 1.5.x, 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1 does not properly validate URLs, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a control character in a URL, as demonstrated by a \\x08javascript: URL.",
      "published_date": "2015-03-25T14:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.20'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.6.11'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.7'}\", \"{'introduced': '1.8a0'}\", \"{'fixed': '1.8c1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-8",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Cross-site scripting (XSS) vulnerability in the contents function in admin/helpers.py in Django before 1.7.6 and 1.8 before 1.8b2 allows remote attackers to inject arbitrary web script or HTML via a model attribute in ModelAdmin.readonly_fields, as demonstrated by a @property.",
      "published_date": "2015-03-12T14:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.7.6'}\", \"{'introduced': '1.8a1'}\", \"{'fixed': '1.8b2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-4",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 allows remote attackers to spoof WSGI headers by using an _ (underscore) character instead of a - (dash) character in an HTTP header, as demonstrated by an X-Auth_User header.",
      "published_date": "2015-01-16T16:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.18'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-5",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The django.util.http.is_safe_url function in Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 does not properly handle leading whitespaces, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a crafted URL, related to redirect URLs, as demonstrated by a \"\\njavascript:\" URL.",
      "published_date": "2015-01-16T16:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.18'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-6",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The django.views.static.serve view in Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 reads files an entire line at a time, which allows remote attackers to cause a denial of service (memory consumption) via a long line in a file.",
      "published_date": "2015-01-16T16:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.18'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2015-7",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "ModelMultipleChoiceField in Django 1.6.x before 1.6.10 and 1.7.x before 1.7.3, when show_hidden_initial is set to True, allows remote attackers to cause a denial of service by submitting duplicate values, which triggers a large number of SQL queries.",
      "published_date": "2015-01-16T16:59:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.18'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.6.10'}\", \"{'introduced': '1.7'}\", \"{'fixed': '1.7.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-4",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not properly validate URLs, which allows remote attackers to conduct phishing attacks via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated.",
      "published_date": "2014-08-26T14:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-5",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.",
      "published_date": "2014-08-26T14:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-6",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The contrib.auth.middleware.RemoteUserMiddleware middleware in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3, when using the contrib.auth.backends.RemoteUserBackend backend, allows remote authenticated users to hijack web sessions via vectors related to the REMOTE_USER header.",
      "published_date": "2014-08-26T14:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-7",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The administrative interface (contrib.admin) in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not check if a field represents a relationship between models, which allows remote authenticated users to obtain sensitive information via a to_field parameter in a popup action to an admin change form page, as demonstrated by a /admin/auth/user/?pop=1&t=password URI.",
      "published_date": "2014-08-26T14:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '2b31342cdf14fc20e07c43d258f1e7334ad664a6'}\", \"{'introduced': '0'}\", \"{'fixed': '1.4.14'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.9'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.6'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-19",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly include the (1) Vary: Cookie or (2) Cache-Control header in responses, which allows remote attackers to obtain sensitive information or poison the cache via a request from certain browsers.",
      "published_date": "2014-05-16T15:55:00Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.13'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.8'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.5'}\", \"{'introduced': '1.7a0'}\", \"{'fixed': '1.7b4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-20",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\"",
      "published_date": "2014-05-16T15:55:00Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.13'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.8'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.5'}\", \"{'introduced': '1.7a0'}\", \"{'fixed': '1.7b4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-1",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"",
      "published_date": "2014-04-23T15:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.11'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.6'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-2",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The caching framework in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 reuses a cached CSRF token for all anonymous users, which allows remote attackers to bypass CSRF protections by reading the CSRF cookie for anonymous users.",
      "published_date": "2014-04-23T15:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.11'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.6'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2014-3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The (1) FilePathField, (2) GenericIPAddressField, and (3) IPAddressField model field classes in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 do not properly perform type conversion, which allows remote attackers to have unspecified impact and vectors, related to \"MySQL typecasting.\"",
      "published_date": "2014-04-23T15:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.4.11'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.6'}\", \"{'introduced': '1.6'}\", \"{'fixed': '1.6.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2013-19",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Cross-site scripting (XSS) vulnerability in the AdminURLFieldWidget widget in contrib/admin/widgets.py in Django 1.5.x before 1.5.2 and 1.6.x before 1.6 beta 2 allows remote attackers to inject arbitrary web script or HTML via a URLField.",
      "published_date": "2013-10-04T17:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '90363e388c61874add3f3557ee654a996ec75d78'}\", \"{'fixed': 'cbe6d5568f4f5053ed7228ca3c3d0cce77cf9560'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2013-21",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The is_safe_url function in utils/http.py in Django 1.4.x before 1.4.6, 1.5.x before 1.5.2, and 1.6 before beta 2 treats a URL's scheme as safe even if it is not HTTP or HTTPS, which might introduce cross-site scripting (XSS) or other vulnerabilities into Django applications that use this function, as demonstrated by \"the login view in django.contrib.auth.views\" and the javascript: scheme.",
      "published_date": "2013-10-04T17:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': 'ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a'}\", \"{'fixed': 'ae3535169af804352517b7fea94a42a1c9c4b762'}\", \"{'fixed': '1a274ccd6bc1afbdac80344c9b6e5810c1162b5f'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.6'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2013-18",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The authentication framework (django.contrib.auth) in Django 1.4.x before 1.4.8, 1.5.x before 1.5.4, and 1.6.x before 1.6 beta 4 allows remote attackers to cause a denial of service (CPU consumption) via a long password which is then hashed.",
      "published_date": "2013-09-23T20:55:00Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.8'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2013-20",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Directory traversal vulnerability in Django 1.4.x before 1.4.7, 1.5.x before 1.5.3, and 1.6.x before 1.6 beta 3 allows remote attackers to read arbitrary files via a file path in the ALLOWED_INCLUDE_ROOTS setting followed by a .. (dot dot) in a ssi template tag.",
      "published_date": "2013-09-16T19:14:00Z",
      "affected_versions": "[\"{'introduced': '1.4'}\", \"{'fixed': '1.4.7'}\", \"{'introduced': '1.5'}\", \"{'fixed': '1.5.3'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2013-16",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The administrative interface for Django 1.3.x before 1.3.6, 1.4.x before 1.4.4, and 1.5 before release candidate 2 does not check permissions for the history view, which allows remote authenticated administrators to obtain sensitive object history information.",
      "published_date": "2013-05-02T14:55:00Z",
      "affected_versions": "[\"{'introduced': '1.3'}\", \"{'fixed': '1.3.6'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2013-17",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The form library in Django 1.3.x before 1.3.6, 1.4.x before 1.4.4, and 1.5 before release candidate 2 allows remote attackers to bypass intended resource limits for formsets and cause a denial of service (memory consumption) or trigger server errors via a modified max_num parameter.",
      "published_date": "2013-05-02T14:55:00Z",
      "affected_versions": "[\"{'introduced': '1.3'}\", \"{'fixed': '1.3.6'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2012-7",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The django.http.HttpRequest.get_host function in Django 1.3.x before 1.3.4 and 1.4.x before 1.4.2 allows remote attackers to generate and display arbitrary URLs via crafted username and password Host header values.",
      "published_date": "2012-11-18T23:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '9305c0e12d43c4df999c3301a1f0c742264a657e'}\", \"{'fixed': 'b45c377f8f488955e0c7069cad3f3dd21910b071'}\", \"{'fixed': '92d3430f12171f16f566c9050c40feefb830a4a3'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.4'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2012-2",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The (1) django.http.HttpResponseRedirect and (2) django.http.HttpResponsePermanentRedirect classes in Django before 1.3.2 and 1.4.x before 1.4.1 do not validate the scheme of a redirect target, which might allow remote attackers to conduct cross-site scripting (XSS) attacks via a data: URL.",
      "published_date": "2012-07-31T17:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.3.2'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2012-3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The django.forms.ImageField class in the form system in Django before 1.3.2 and 1.4.x before 1.4.1 completely decompresses image data during image validation, which allows remote attackers to cause a denial of service (memory consumption) by uploading an image file.",
      "published_date": "2012-07-31T17:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.3.2'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2012-4",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The get_image_dimensions function in the image-handling functionality in Django before 1.3.2 and 1.4.x before 1.4.1 uses a constant chunk size in all attempts to determine dimensions, which allows remote attackers to cause a denial of service (process or thread consumption) via a large TIFF image.",
      "published_date": "2012-07-31T17:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.3.2'}\", \"{'introduced': '1.4'}\", \"{'fixed': '1.4.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-1",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "django.contrib.sessions in Django before 1.2.7 and 1.3.x before 1.3.1, when session data is stored in the cache, uses the root namespace for both session identifiers and application-data keys, which allows remote attackers to modify a session by triggering use of a key that is equal to that session's identifier.",
      "published_date": "2011-10-19T10:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-2",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.",
      "published_date": "2011-10-19T10:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a HEAD request, but then uses a GET request for the new target URL in the case of a redirect, which might allow remote attackers to trigger arbitrary GET requests with an unintended source IP address via a crafted Location header.",
      "published_date": "2011-10-19T10:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-4",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django before 1.2.7 and 1.3.x before 1.3.1 uses a request's HTTP Host header to construct a full URL in certain circumstances, which allows remote attackers to conduct cache poisoning attacks via a crafted request.",
      "published_date": "2011-10-19T10:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-5",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The CSRF protection mechanism in Django through 1.2.7 and 1.3.x through 1.3.1 does not properly handle web-server configurations supporting arbitrary HTTP Host headers, which allows remote attackers to trigger unauthenticated forged requests via vectors involving a DNS CNAME record and a web page containing JavaScript code.",
      "published_date": "2011-10-19T10:55:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.2.7'}\", \"{'introduced': '1.3'}\", \"{'fixed': '1.3.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-10",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Django 1.1.x before 1.1.4 and 1.2.x before 1.2.5 does not properly validate HTTP requests that contain an X-Requested-With header, which makes it easier for remote attackers to conduct cross-site request forgery (CSRF) attacks via forged AJAX requests that leverage a \"combination of browser plugins and redirects,\" a related issue to CVE-2011-0447.",
      "published_date": "2011-02-14T21:00:00Z",
      "affected_versions": "[\"{'introduced': '1.1'}\", \"{'fixed': '1.1.4'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-11",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Cross-site scripting (XSS) vulnerability in Django 1.1.x before 1.1.4 and 1.2.x before 1.2.5 might allow remote attackers to inject arbitrary web script or HTML via a filename associated with a file upload.",
      "published_date": "2011-02-14T21:00:00Z",
      "affected_versions": "[\"{'introduced': '1.1'}\", \"{'fixed': '1.1.4'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-12",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Directory traversal vulnerability in Django 1.1.x before 1.1.4 and 1.2.x before 1.2.5 on Windows might allow remote attackers to read or execute files via a / (slash) character in a key in a session cookie, related to session replays.",
      "published_date": "2011-02-14T21:00:00Z",
      "affected_versions": "[\"{'introduced': '1.1'}\", \"{'fixed': '1.1.4'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.5'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-8",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The administrative interface in django.contrib.admin in Django before 1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not properly restrict use of the query string to perform certain object filtering, which allows remote authenticated users to obtain sensitive information via a series of requests containing regular expressions, as demonstrated by a created_by__password__regex parameter.",
      "published_date": "2011-01-10T20:00:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1.3'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2011-9",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The password reset functionality in django.contrib.auth in Django before 1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not validate the length of a string representing a base36 timestamp, which allows remote attackers to cause a denial of service (resource consumption) via a URL that specifies a large base36 integer.",
      "published_date": "2011-01-10T20:00:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1.3'}\", \"{'introduced': '1.2'}\", \"{'fixed': '1.2.4'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2010-12",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Cross-site scripting (XSS) vulnerability in Django 1.2.x before 1.2.2 allows remote attackers to inject arbitrary web script or HTML via a csrfmiddlewaretoken (aka csrf_token) cookie.",
      "published_date": "2010-09-14T19:00:00Z",
      "affected_versions": "[\"{'introduced': '1.2'}\", \"{'fixed': '1.2.2'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2009-4",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Algorithmic complexity vulnerability in the forms library in Django 1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial of service (CPU consumption) via a crafted (1) EmailField (email address) or (2) URLField (URL) that triggers a large amount of backtracking in a regular expression.",
      "published_date": "2009-10-13T10:30:00Z",
      "affected_versions": "[\"{'introduced': '1.0'}\", \"{'fixed': '1.0.4'}\", \"{'introduced': '1.1'}\", \"{'fixed': '1.1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2009-3",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The Admin media handler in core/servers/basehttp.py in Django 1.0 and 0.96 does not properly map URL requests to expected \"static media files,\" which allows remote attackers to conduct directory traversal attacks and read arbitrary files via a crafted URL.",
      "published_date": "2009-08-04T16:30:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2008-2",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The administration application in Django 0.91, 0.95, and 0.96 stores unauthenticated HTTP POST requests and processes them after successful authentication occurs, which allows remote attackers to conduct cross-site request forgery (CSRF) attacks and delete or modify data via unspecified requests.",
      "published_date": "2008-09-04T17:41:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2008-1",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "Cross-site scripting (XSS) vulnerability in the login form in the administration application in Django 0.91 before 0.91.2, 0.95 before 0.95.3, and 0.96 before 0.96.2 allows remote attackers to inject arbitrary web script or HTML via the URI of a certain previous request.",
      "published_date": "2008-05-23T15:32:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1'}\"]",
      "patched_versions": "[]"
    },
    {
      "cve_id": "PYSEC-2007-1",
      "severity": "UNKNOWN",
      "cvss_score": null,
      "description": "The internationalization (i18n) framework in Django 0.91, 0.95, 0.95.1, and 0.96, and as used in other products such as PyLucid, when the USE_I18N option and the i18n component are enabled, allows remote attackers to cause a denial of service (memory consumption) via many HTTP requests with large Accept-Language headers.",
      "published_date": "2007-10-30T19:46:00Z",
      "affected_versions": "[\"{'introduced': '0'}\", \"{'fixed': '1.1'}\"]",
      "patched_versions": "[]"
    }
  ]
}